@startuml

!include ../dist/common.puml
!include ../dist/all.puml

header Техкружок 
title 1C Enterpise example
caption Пример диаграммы объектов
footer Команда ИТК, 2022

package НСИ <<folder>> {

    _ОпределяемыйТип(Товар, "Товар")

    _Справочник(ТоварныеКатегории, "Товарные категории")
    _Справочник(Склад, "Склады")
    _Справочник(Номенклатура, "Номенклатура")
    _Справочник(Характеристика, "Значения характеристик товаров")

    _ПВХ(ВидыХарактеристикТоваров, "Виды характеристик товаров")

    _РегистрСведений(АналогиНоменклатуры, "Аналоги номенклатуры") {
        <$d> Номенклатура
        <$r> Аналог
    }

}

package СкладскойУчет <<folder>> {

    _Документ(ПриходныйОрдерНаСклад, "Приходный ордер") {
        Склад
        ВидОперации
        -- Товары --
        Товар
        ВидХарактеристики
        Характеристика
        Количество
        Сумма
    }

    _Документ(РасходныйОрдерНаСклад, "Расходный ордер") {
        Склад
        ВидОперации
        -- Товары --
        Товар
        ВидХарактеристики
        Характеристика
        Количество
        Сумма
    }

    _Перечисление(ВидОперацииПриходныйОрдер, "Вид операции приходный ордер"){
        ПоступлениеТоваров
        ВозвратТоваров
    }
    _Перечисление(ВидОперацииРасходныйОрдер, "Вид операции расходный ордер"){
        РасходСоСклада
        Списание
    }

    _РегистрНакопления(ТоварыНаСкладах, "Товары на складах") {
        <$d> Товар
        <$d> ВидХарактеристики
        <$d> Характеристика
        <$d> Склад
        <$r> Количество    
    }
}

ТоварныеКатегории --- Товар
Номенклатура --- Товар
Номенклатура --- АналогиНоменклатуры::Номенклатура
Номенклатура --- АналогиНоменклатуры::Аналог

Товар --> ПриходныйОрдерНаСклад::Товар
Товар --> РасходныйОрдерНаСклад::Товар
Товар --> ТоварыНаСкладах::Товар

Склад --> ПриходныйОрдерНаСклад::Склад
Склад --> РасходныйОрдерНаСклад::Склад
Склад --> ТоварыНаСкладах::Склад

ВидОперацииПриходныйОрдер --> ПриходныйОрдерНаСклад::ВидОперации
ВидОперацииРасходныйОрдер --> РасходныйОрдерНаСклад::ВидОперации

ВидыХарактеристикТоваров --> Характеристика : Владелец
ВидыХарактеристикТоваров --> ТоварыНаСкладах::ВидХарактеристики
ВидыХарактеристикТоваров --> ПриходныйОрдерНаСклад::ВидХарактеристики
ВидыХарактеристикТоваров --> РасходныйОрдерНаСклад::ВидХарактеристики

Характеристика --> ТоварыНаСкладах::Характеристика
Характеристика --> ПриходныйОрдерНаСклад::Характеристика
Характеристика --> РасходныйОрдерНаСклад::Характеристика

ПриходныйОрдерНаСклад --> ТоварыНаСкладах
РасходныйОрдерНаСклад --> ТоварыНаСкладах

@enduml